version: '3.8'

x-logging:
  &default-logging
  options:
    max-size: '20m'
    max-file: '3'
  driver: json-file  

services:

  postgres:
    image:   postgres:16.3
    container_name: postgres
    restart: unless-stopped
    logging: *default-logging
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asr

  dbmigrate:
    image:   airenas/bt-dbmigrate:${MIGRATE_VERSION}
    logging: *default-logging
    environment:
      - DATABASE_URL=${POSTGRES_URL}
    depends_on:
      - postgres  
