version: '3.8'

x-logging:
  &default-logging
  options:
    max-size: '20m'
    max-file: '3'
  driver: json-file  

services:

  postgres:
    image:   postgres:16.3
    container_name: postgres
    restart: unless-stopped
    logging: *default-logging
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asr

  dbmigrate:
    image:   airenas/bt-dbmigrate:${VERSION}
    logging: *default-logging
    environment:
      - DATABASE_URL=${POSTGRES_URL}
    depends_on:
      - postgres  

  worker:
    image:   airenas/bt-worker:${VERSION}
    logging: *default-logging
    volumes:
      - ./.data:/data:rw
    user: 1000:1000  
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - BASE_DIR=/data
      - ASR_URL=https://atpazinimas.intelektika.lt/ausis
      - RUST_LOG=INFO

  keeper:
    image:   airenas/bt-sound-keeper:${VERSION}
    logging: *default-logging
    volumes:
      - ./.data:/data:rw
    user: 1000:1000 
    ports:
      - "8001:8000" 
    environment:
      - BASE_DIR=/data
      - RUST_LOG=INFO

  upload-gui:
    image:   airenas/bt-upload-gui:${VERSION}
    logging: *default-logging
    ports:
      - "8002:8000"
    environment:
      - BASE_PATH=/test
      - SERVER_URL=http://localhost:8001/upload

    