version: '3.8'

x-logging:
  &default-logging
  options:
    max-size: '20m'
    max-file: '3'
  driver: json-file  

services:

  traefik:
    container_name: traefik
    image: traefik:v2.10
    command:
      - --entrypoints.web.address=:80
      - --log.level=debug
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --api
    ports:
      - "8080:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  postgres:
    image:   postgres:16.3
    container_name: postgres
    restart: unless-stopped
    logging: *default-logging
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asr

  dbmigrate:
    image:   airenas/bt-dbmigrate:${VERSION}
    logging: *default-logging
    restart: on-failure
    environment:
      - DATABASE_URL=${POSTGRES_URL}
    depends_on:
      - postgres  

  worker:
    image:   airenas/bt-worker:${VERSION}
    logging: *default-logging
    volumes:
      - ./.data:/data:rw
    user: 1000:1000  
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - BASE_DIR=/data
      - ASR_URL=https://atpazinimas.intelektika.lt/ausis
      - RUST_LOG=INFO

  keeper:
    image:   airenas/bt-sound-keeper:${VERSION}
    logging: *default-logging
    volumes:
      - ./.data:/data:rw
    user: 1000:1000 
    ports:
      - "8001:8000" 
    environment:
      - BASE_DIR=/data
      - RUST_LOG=INFO

  upload-gui:
    image:   airenas/bt-upload-gui:${GUI_VERSION}
    logging: *default-logging
    # ports:
    #   - "8002:8000"
    environment:
      - BASE_PATH=/audio-upload/
      - SERVER_URL=http://localhost:8001/upload
    labels:
     - "traefik.enable=true" 
     - "traefik.http.routers.upload.rule=PathPrefix(`/audio-upload`)"
     - "traefik.http.routers.upload.middlewares=upload"
     - "traefik.http.routers.upload.entrypoints=web"
     - "traefik.http.middlewares.upload.stripprefix.prefixes=/audio-upload"
     - "traefik.http.services.upload.loadbalancer.server.port=8000"  
    