--SQL statements for a work table
CREATE TABLE work_data(
    id TEXT NOT NULL PRIMARY KEY,
    external_ID TEXT NOT NULL,
    file_name TEXT NOT NULL DEFAULT '',
    base_dir TEXT NOT NULL DEFAULT '',
    try_count INT NOT NULL DEFAULT 0,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
