name: rust

on:
  push:
    branches: [ main]
    paths:
      - "transcriber/**"
  pull_request:
    branches: [ main ]
    paths:
      - "transcriber/**"

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./transcriber
    steps:
      - uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: clippy
      - name: Check format 
        run: make test/format   

      - name: Build 
        run: make build/local     

      - name: Lint 
        run: make test/lint

      - name: Test 
        run: make test/unit     

      - name: Install requirements 
        run: make install/checks

      - name: Audit 
        run: make audit
        continue-on-error: true 

      - name: Coverage 
        run: cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
